spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yeoyewon97@gmail.com
    password: gyyw071756-
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true